version: '3'

services:

  s3finder:
    build:
      context: .
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
        # - AWS_ACCESS_KEY_ID=${ODC_ACCESS_KEY}
        # - AWS_SECRET_ACCESS_KEY=${ODC_SECRET_KEY}
    ports:
      - "8889:8888"
    volumes:
      - ./data:/notebooks
    shm_size: 1g
    command: jupyter notebook --ip="*" --NotebookApp.token=''
